sudo: required # required root permission
services: #required dependencies
  - docker

before_install:
  - docker build -t razmjo/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true razmjo/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  skip_cleanup: true
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-843594982021"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY