language: generic
sudo: required # required root permission
services: #required dependencies
  - docker

before_install:
  - docker build -t razmjo/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true razmjo/frontend npm run test

deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: 'us-east-1'
  app: 'jobsaf-test'
  env: 'Jobsaftest-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-843594982021'
  bucket_path: 'jobsaf-test'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY