sudo: required # required root permission
services: #required dependencies
  - docker

before_install:
  - docker build -t razmjo/frontend -f Dockerfile.dev .

script:
  - docker run razmjo/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-843594982021"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"